# File: .docker/docker-compose.yml
services:
  solver:
    build:
      context: .
      dockerfile: Dockerfile.python
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - MPLCONFIGDIR=/tmp/matplotlib
    volumes:
      - ..:/app
    ports:
      - "5000:5000"
    command: bash -c "python3 solver.py"

  server:
    extends: solver
    command: bash -c "python3 server.py"
