FROM python:3.12-slim-bookworm

# Avoid prompts from apt
ENV DEBIAN_FRONTEND=noninteractive


# Set the working directory in the container
WORKDIR /app

# Install system dependencies and TeX Live
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    libffi-dev \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements file
COPY req.txt .

# Install Python packages
RUN pip install --no-cache-dir -r req.txt

CMD ["python3 main.py"]